Authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('signup/', views.signupPage, name='signup'),
    path('logout/', views.Logout, name='logout'),
    path('updateprofile/' ,views.update_user_information, name='updateProfile')
]

JojoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import  settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('Authentication.urls')),
    path('', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name='home'),
    path('post/<str:pk>/', views.view_post, name='post'),
    path('deletePost/<str:pk>/', views.delete_post, name='delete'),
    path('profile/', views.profile_page, name='profile'),
    path('addpost/', views.add_post, name='addpost'),
    path('editpost/<str:pk>', views.edit_post, name='editpost'),
    path('about/', views.about_page, name='about'),
]

Authentication/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    username = models.CharField(max_length=50, null=True, blank=True, unique=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    phone = models.IntegerField(null=True, blank=True)
    profile_img = models.ImageField( upload_to=f'./profile/{username}/', null=True,blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.username

blog/models.py
from django.db import models
from Authentication.models import Profile


# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    Post = models.TextField(null=True, blank=True)
    logo = models.ImageField('head image', null=True, blank=True)
    pub_date = models.DateField('Date Published', auto_now=True)
    pub_time = models.TimeField('Time Published', auto_now=True)
    Author = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import BlogPost


class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'
        exclude = ['Author']


class TestForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = '__all__'

Authentication/views.py
from PIL import Image
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages import error, info
from django.shortcuts import redirect, render



from .authform import ProfileForm, UpdateForm, loginForm, signupForm
from .isauth import is_authenticated
# Create your views here.
from .models import Profile


@is_authenticated
def loginPage(request):
    if request.method == 'POST':

        form = loginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
            else:
                error(request, 'The username or password is incorrect')

    return render(request, 'Authentication/LoginPage.html')


def signupPage(request):
    if request.method == 'POST':
        form = signupForm(request.POST)
        p_form = ProfileForm(request.POST)

        if form.is_valid() and p_form.is_valid():
            # username,firstname,lastname,email, password1, password2 = form.cleaned_data.get('username'), form.cleaned_data.get('firstname') ,form.cleaned_data.get('lastname'), form.cleaned_data.get('email'), form.cleaned_data.get('password1'),form.cleaned_data.get('password2')
            user = form.save()
            profile = p_form.save(commit=False)
            profile.user = user
            profile.save()

            info(request, "User created successfully, Login Now")
            return redirect('login')
        else:
            error(request, form.errors.as_text())
    return render(request, 'Authentication/SignupPage.html')


def Logout(request):
    logout(request)
    return redirect('login')


def update_user_information(request, **kwargs):
    if request.method == 'POST':
        print(request.POST)
        print(request.FILES)
        profile_form = ProfileForm(request.POST,request.FILES, instance=request.user)
        update_form = UpdateForm(request.POST, instance=request.user)
        print(profile_form.errors)
        if profile_form.is_valid() and update_form.is_valid():
            user = Profile.objects.get(user=request.user)
            print(user)
            user.username = profile_form.cleaned_data['username']
            user.last_name = profile_form.cleaned_data['last_name']
            user.first_name = profile_form.cleaned_data['first_name']
            if request.FILES:
                user.profile_img =profile_form.cleaned_data['profile_img']
            user.save()
            update_form.save()

            return redirect('profile')
        else:
            error(request, 'failed')
            return redirect('profile')

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import BlogPost


# Create your views here.

@login_required(login_url='login')
def index(req):
    posts = BlogPost.objects.all()
    context = {'posts': posts}
    context["postOwner"] = req.user.profile
    if req.user.is_staff:
        context['is_admin'] = True
    else:
        pass

    return render(req, 'blog/index.html', context=context)


@login_required(login_url='login')
def view_post(req, pk):
    post = get_object_or_404(BlogPost.objects.all(), pk=pk)
    context = {'post': post}
    if req.user.is_staff:
        context['is_admin'] = True
    else:
        pass
    return render(req, 'blog/post.html', context=context)


@login_required(login_url='login')
def profile_page(req):
    user = req.user
    user_post = BlogPost.objects.filter(Author=req.user.profile)
    context: dict = {'user': user, 'posts': user_post}

    return render(req, 'blog/profile.html', context=context)


@login_required(login_url='login')
def add_post(req) -> HttpResponse:
    form: PostForm = PostForm(instance=req.user.profile)
    context: dict = {'post': form}
    if req.method == 'POST':
        post = PostForm(req.POST, req.FILES)

        if post.is_valid():
            post = post.save(commit=False)
            post.Author = req.user.profile
            post.save()

            return redirect('home')
   

    return render(req, 'blog/add_post.html', context=context)

@login_required(login_url='login')
def edit_post(req, pk) -> HttpResponse:
    post_item = BlogPost.objects.get(pk=pk)
    form: PostForm = PostForm(instance=post_item)
    context: dict = {'post': form}
    if req.method == 'POST':
        post = PostForm(req.POST, req.FILES)

        if post.is_valid():
            post_item._do_update(post)
            # post_item.title = post.title
            # post_item.Post = post.Post
            # post.logo = post.logo

            return redirect('home')


    return render(req, 'blog/add_post.html', context=context)


@login_required(login_url='login')
def edit_post(req, pk) -> HttpResponse:
    post = BlogPost.objects.get(pk=pk)
    form: PostForm = PostForm(instance=post)
    context: dict = {'post': form, 'id':pk}
    if req.method == 'POST':
        post = PostForm(req.POST, req.FILES, instance=post)

        if post.is_valid():
            post = post.save()

            return redirect('home')


    return render(req, 'blog/edit_post.html', context=context)


@login_required(login_url='login')
def about_page(req):
    return render(req, 'blog/about.html')


@login_required(login_url='login')
def delete_post(request, pk):
    if request.method == 'DELETE':
        post = BlogPost.objects.get(pk=pk)
        post.delete()
        return HttpResponse(status=200)
    else:
        return HttpResponse(status=407)

Authentication/templates/Authentication/LoginPage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width , initial-scale=1.0 , maximum-scale=1">
    <meta charset="UTF-8">
    <link href="{% static 'Authentication/css/login.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'JT.ico' %}">
    <title>Login</title>
</head>
<body>
<div>
    <div class="login-con">
        <h1 class="text-center">Login Now</h1>
        <hr>
        <form method="post">
        {% csrf_token %}
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="input-group">
                <input type="submit" class="lgbtn" value="Login">
            </div>
            {% if messages %}
                {% for message in messages %}
                    <p class="text-center", style="margin-block:5px">{{ message}}</p>
                {% endfor %}
            {% endif %}
            <p class="text-center"> Don't have an account ?. <a href="{% url 'signup' %}" style="color: dodgerblue">Sign Up Here</a></p>

        </form>
    </div>
</div>

</body>
</html>

Authentication/templates/Authentication/SignupPage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width , initial-scale=1.0 , maximum-scale=1">
    <meta charset="UTF-8">
    <link href="{% static 'Authentication/css/signup.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'JT.ico' %}">

    <title>Login</title>
</head>
<body>
<div>
    <div class="signup-con">
        <h1 class="text-center">Signup Now</h1>
        <hr>
        <form method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="input-group">
                <label for="firstname">Firstname</label>
                <input type="text" id="firstname" name="first_name" required>
            </div>
            <div class="input-group">
                <label for="lastname">Lastname</label>
                <input type="text" id="lastname" name="last_name" required>
            </div>
            <div class="input-group">
                <label for="email">Email</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="input-group">
                <label for="password1">Password</label>
                <input type="password" id="password1" name="password1" required>
            </div>
            <div class="input-group">
                <label for="password2">Confirm Password</label>
                <input type="password" id="password2" name="password2" required>
            </div>
            <div class="input-group">
                <input type="submit" class="lgbtn" value="Sign Up">
            </div>
            {% if messages %}
                {% for message in messages %}
                    <p class="text-center" , style="margin-block:5px">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <p class="text-center"> Already have an account ?. <a href="{% url 'login' %}" style="color: dodgerblue">login Now</a></p>

        </form>
    </div>
</div>



</body>
</html>

blog/templates/blog/Footer.html
    <footer>
        <div class="container">
            <h1>
                Jojo's <span>Blog</span>
            </h1>
            <p>copyright&copy;2022</p>
        </div>
    </footer>

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static "blog/css/about.css" %}">
{% endblock %}
{% block content %}
    <main class="about-me">
        <div class="img-con">
            <img src="{% static "blog/images/120171859_2074344169364441_8922802070400517458_n.jpg" %}"/>
        </div>
        <h3 class="about-head">
            About Me
        </h3>

        <p>
            I Joseph Thomas, I'm an adventurer exploring the vast land of web development and picking up XP point along
            the way.
        </p>
        <p>
            So far in my journey I've traveled through the town of <b>React.js</b> and it was marvelous, while there I
            learnt about SPA and the beauty of it.
        </p>
        <p>
            Now I'm exploring the city of <b>Django</b> in the country of <b>Python</b>, and this is one of my Projects
        </p>
        <p> If you want to see the code <a href="https://github.com/jojothomas1515/JojoProject" >Click Here</a></p>
        <p> Check me out on  <a href="https://www.linkedin.com/in/joseph-thomas-551452210/" target="_blank">LinkedIn</a></p>


        </div>
    </main>
{% endblock %}

blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block extrahead %}
<script src="https://cdn.tiny.cloud/1/vvnjdihxjvesyvkw33xlcxniivipwdkyyj0yj9ha3xsqbj5g/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>    <script src="{% static 'blog/js/mice.js' %}" type="module"></script>
    <link rel="stylesheet" href="{% static 'blog/css/post_form.css' %}"/>

{% endblock %}

{% block content %}
    {% if post %}
        <div class="post-form-con">
            <form action="{% url 'addpost' %}" method="post" class="postform" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="post-form-grid">
                    <div class="g-1"><label for="id_title">{{ post.title.label }}</label>{{ post.title }}</div>
                    <div class="g-2"><label for="id_logo"><i class="fa fa-add fa-3x"></i> </label><div>{{ post.logo }}</div><p id="img_name">Cover Image</p></div>
                    <div class="g-4">  {{ post.Post }}</div>
                    <div class="submit-post-btn"><button class="sub-btn">Click here to Post</button></div>
                </div>

            </form>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% block extrahead %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width ,initial-scale=1.0, maximum-scale=1, height=device-height">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    {#tailwind css cdn#}
    <link rel="stylesheet" href="{% static 'blog/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/footer.css' %}">
    <script src="{% static 'blog/js/nav.js' %}" defer></script>
    <link rel="icon" type="image/x-icon" href="{% static 'JT.ico' %}">
    <meta charset="UTF-8">
    <title>JojoThomas</title>
</head>
<body>
{% include 'blog/navbar.html' %}
{% block content %}
{% endblock %}
{% include 'blog/Footer.html' %}
</body>
</html>

blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block extrahead %}
    <script src="https://cdn.tiny.cloud/1/vvnjdihxjvesyvkw33xlcxniivipwdkyyj0yj9ha3xsqbj5g/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="{% static 'blog/js/mice.js' %}" type="module"></script>
    <link rel="stylesheet" href="{% static 'blog/css/post_form.css' %}"/>

{% endblock %}

{% block content %}
    {% if post %}
        <div class="post-form-con">
            <form action="{% url 'editpost' id %}" method="post" class="postform" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="post-form-grid">
                    <div class="g-1"><label for="id_title">{{ post.title.label }}</label>{{ post.title }}</div>
                    <div class="g-2"><label for="id_logo"><i class="fa fa-add fa-3x"></i> </label>
                        <div>{{ post.logo }}</div>
                        <p id="img_name">Cover Image</p></div>
                    <div class="g-4">  {{ post.Post }}</div>
                    <div class="submit-post-btn">
                        <button class="sub-btn">Click here to Post</button>
                    </div>
                </div>

            </form>
        </div>
    {% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static "/blog/css/index.css" %}">
    <script src="{% static 'blog/js/index.js' %}" defer></script>
{% endblock %}

{% block content %}
    {% if is_admin %}
        <div style="background:rgba(0,0,0,.6)">
            <a href="/admin/" class="btn" style="margin-inline:auto; color:white;">admin panel</a>
        </div>
    {% endif %}
    <section class="intro" style="background-image:url('{% static 'blog/images/yikr9jXET.jpg' %}')">
        <div class="container">
            <h1>
                Jojo's Page
            </h1>
            <h3>Interact and Connect</h3>

            <p>To know more about us </p>
            <a href="{% url 'about' %}" class="btn"> click here</a>
        </div>
    </section>
    <section class="feed">
        <div class="center-container">
            <div class="feed-con container">
                {% for post in posts %}
                    <div class="card">
                        {% if post.Author == postOwner %}
                            <i class="opt-icon fa fa-bars"></i>
                            <div class="option" style="display: none">
                                <button class="option-items" id="delete-post" data-postId="{{ post.id }}">
                                    delete post
                                </button>
                                <button class="option-items" id="edit-post" data-postId="{{ post.id }}">
                                    Edit post
                                </button>
                            </div>
                        {% endif %}
                        <a href="{% url "post" post.id %}">
                            <h4 class="card-header">{{ post.title }}</h4>
                            <div class="card-img-con">
                                <img src="



                                        {% if post.logo %}{{ post.logo.url }}{% else %} {% static 'blog/images/cool.jpg' %}{% endif %}"
                                     alt="no picture">
                            </div>
                            <sub class="">{{ post.pub_date }} {{ post.pub_time }}</sub>
                            <p><sub class="">Author: {{ post.Author }} </sub></p>

                        </a>
                    </div>
                {% endfor %}
            </div>

        </div>
    </section>

{% endblock %}

blog/templates/blog/navbar.html
<div class="navbar">
    <div class="navbar-con ">
        <a class="logo-link" href="{% url 'home' %}"><h1> Jojo's <span>Page</span></h1></a>

        <nav class="">
            <label for="check"> <i class="fa fa-bars fa-2x bars" data-navbars></i>
            </label>
            <input type="checkbox" id="check">
            <ul class="nav-items">
                <a href="{% url 'home' %}" class="btn link-btn">Home</a>
                <a href="{% url 'profile' %}" class="btn link-btn">Profile</a>
                <a href="{% url 'addpost' %}" class="btn link-btn">Add Post</a>
                <a href="{% url 'about' %}" class="btn link-btn">About</a>
                <a href="{% url 'logout' %}" class="btn link-logout"><i class="fas fa-door-open"></i> </a>

            </ul>
        </nav>

    </div>

</div>

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if is_admin %}
        <div style="background:rgba(0,0,0,.6)">
            <a href="/admin/" class="btn" style="margin-inline:auto; color:white;">admin panel</a>
        </div>
    {% endif %}
    <div style="min-height: 80vh; padding:2rem 1rem ; background-color: aliceblue">
    {% if post %}
        {{ post.Post|safe}}
    {% endif %}
    </div>

{% endblock %}

blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load static %}
{% block extrahead %}
    <link rel="stylesheet" href="{% static 'blog/css/profile_page.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'blog/css/profile_post.css' %}" type="text/css">
    <script rel="script" src="{% static 'blog/js/prof.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block content %}
    {% if is_admin %}
        <div style="background:rgba(0,0,0,.6)">
            <a href="/admin/" class="btn" style="margin-inline:auto; color:white;">admin panel</a>
        </div>
    {% endif %}

    <div class="pp-con">
        <div class='profile-container'>
            <div class="profile">
                <i class="fa fa-user-edit" id="edit-user" data-user-edit-icon></i>
                <div class="p-i-c">
                    {% if user.profile.profile_img %}
                        <a href="{{ user.profile.profile_img.url }}" id="img_link" target="_blank"><img
                                alt="profile_image"
                                src="{{ user.profile.profile_img.url }}"/></a>
                    {% else %}
                        <a href="{% static 'blog/images/cool.jpg' %}" id="img_link" target="_blank"><img
                                alt="profile_image"
                                src="{% static 'blog/images/cool.jpg' %}"/></a>
                    {% endif %}
                </div>
                <p class="info"><span class="secondary">Username :</span> {{ user.profile.username }}</p>
                <p class="info"><span class="secondary">Email : </span>{{ user.email }}</p>
                <p class="info"><span class="secondary">First Name : </span>{{ user.profile.first_name }}</p>
                <p class="info"><span class="secondary">Last Name : </span>{{ user.profile.last_name }}</p>
            </div>
            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% endif %}
        </div>
        {% include 'blog/profile_post.html' %}

        <div class="modal">
            <div class="update-form">
                <i class="fa fa-close" id="close-edit-user" data-user-edit-close></i>
                <form method="post" action="{% url 'updateProfile' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="modal-p-i-c">
                        {% if user.profile.profile_img %}
                            <label for="profile_image_select"><img  alt="profile_image" src="{{ user.profile.profile_img.url }}" id="mi-c"/></label>
                            <input id="profile_image_select" type="file" name="profile_img" data-input-image>
                        {% else %}

                            <label for="profile_image_select"><img alt="profile_image" src="{% static 'blog/images/cool.jpg' %}" id="mi-c"/></label>
                            <input id="profile_image_select" type="file" name="profile_img">
                        {% endif %}

                    </div>
                    <div class="input-group">
                        <label for="username">username</label>
                        <input type="text" name="username" id="username" value="{{ user.username }}" required/>
                    </div>
                    <div class="input-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" value="{{ user.email }}" required/>
                    </div>
                    <div class="input-group">
                        <label for="firstname">First Name</label>
                        <input type="text" name="first_name" id="firstname" value="{{ user.profile.first_name }}"
                               required/>
                    </div>
                    <div class="input-group">
                        <label for="lastname">Last Name</label>
                        <input type="text" name="last_name" id="lastname" value="{{ user.profile.last_name }}"
                               required/>
                    </div>
                    <div class="btn-group">
                        <button type="submit">Update</button>
                    </div>

                </form>
            </div>
        </div>
    </div>




{% endblock %}

blog/templates/blog/profile_post.html
{% load static %}
<section class="posts">
    <h1 class="posts-page-heading">Post</h1>
    <div class="post-con">
        {% for post in posts %}

            <div class="card">
                <i class="opt-icon fa fa-bars"></i>
                <div class="option" style="display: none">
                    <button class="option-items" id="delete-post" data-postId="{{ post.id }}">
                        delete post
                    </button>
                    <button class="option-items" id="edit-post" data-postId="{{ post.id }}">
                        Edit post
                    </button>
                </div>
                <a href="{% url "post" post.id %}">
                    <h4 class="card-header">{{ post.title }} </h4>
                    <div class="card-img-con">
                        <img src="



                                {% if post.logo %}{{ post.logo.url }}{% else %} {% static 'blog/images/cool.jpg' %}{% endif %}"
                             alt="no picture">
                    </div>
                    <p class="">{{ post.summary }}</p>

                    <sub class="">{{ post.pub_date }} {{ post.pub_time }}</sub>
                </a>

            </div>
        {% endfor %}
    </div>
</section>